In [13]:
import numpy as np

In [77]:
# Creating an array
arr = np.random.randint(1, 31, (3, 10))
arr

array([[ 1, 10, 24, 10, 16,  9,  5, 20,  4, 29],
       [ 8, 11, 21, 25,  8,  7, 15, 10, 21, 19],
       [24,  8,  8, 16, 13,  1, 21, 11, 13, 18]])

In [78]:
# 1. Reshaping array
new_arr = arr.reshape(5, 6)
new_arr

array([[ 1, 10, 24, 10, 16,  9],
       [ 5, 20,  4, 29,  8, 11],
       [21, 25,  8,  7, 15, 10],
       [21, 19, 24,  8,  8, 16],
       [13,  1, 21, 11, 13, 18]])

In [79]:
# 2. Addition
new_arr + new_arr

array([[ 2, 20, 48, 20, 32, 18],
       [10, 40,  8, 58, 16, 22],
       [42, 50, 16, 14, 30, 20],
       [42, 38, 48, 16, 16, 32],
       [26,  2, 42, 22, 26, 36]])

In [80]:
# 3. Multiplication
new_arr * new_arr

array([[  1, 100, 576, 100, 256,  81],
       [ 25, 400,  16, 841,  64, 121],
       [441, 625,  64,  49, 225, 100],
       [441, 361, 576,  64,  64, 256],
       [169,   1, 441, 121, 169, 324]])

In [81]:
# 4. division 
new_arr / new_arr

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [82]:
# 5. subraction
new_arr - new_arr

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [83]:
# 6. greater than or equal to
new_arr >= new_arr

array([[ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True]])

In [84]:
# 7. greater than
arr > (arr/1.3)

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [85]:
# 8. sine
np.sin(new_arr)

array([[ 0.84147098, -0.54402111, -0.90557836, -0.54402111, -0.28790332,
         0.41211849],
       [-0.95892427,  0.91294525, -0.7568025 , -0.66363388,  0.98935825,
        -0.99999021],
       [ 0.83665564, -0.13235175,  0.98935825,  0.6569866 ,  0.65028784,
        -0.54402111],
       [ 0.83665564,  0.14987721, -0.90557836,  0.98935825,  0.98935825,
        -0.28790332],
       [ 0.42016704,  0.84147098,  0.83665564, -0.99999021,  0.42016704,
        -0.75098725]])

In [86]:
# 9. Cosine
np.cos(new_arr)

array([[ 0.54030231, -0.83907153,  0.42417901, -0.83907153, -0.95765948,
        -0.91113026],
       [ 0.28366219,  0.40808206, -0.65364362, -0.74805753, -0.14550003,
         0.0044257 ],
       [-0.54772926,  0.99120281, -0.14550003,  0.75390225, -0.75968791,
        -0.83907153],
       [-0.54772926,  0.98870462,  0.42417901, -0.14550003, -0.14550003,
        -0.95765948],
       [ 0.90744678,  0.54030231, -0.54772926,  0.0044257 ,  0.90744678,
         0.66031671]])

In [87]:
# 10. Log
np.log(new_arr)

array([[0.        , 2.30258509, 3.17805383, 2.30258509, 2.77258872,
        2.19722458],
       [1.60943791, 2.99573227, 1.38629436, 3.36729583, 2.07944154,
        2.39789527],
       [3.04452244, 3.21887582, 2.07944154, 1.94591015, 2.7080502 ,
        2.30258509],
       [3.04452244, 2.94443898, 3.17805383, 2.07944154, 2.07944154,
        2.77258872],
       [2.56494936, 0.        , 3.04452244, 2.39789527, 2.56494936,
        2.89037176]])

In [88]:
# 11. Position of min element
np.argmin(new_arr)

0

In [89]:
# 12. Position of max element
np.argmax(new_arr)

9

In [90]:
# 13. Max element in the array
np.max(new_arr)

29

In [91]:
# 14. Minimum element in the array
np.min(new_arr)

1

In [92]:
# 15. Sum of all array elements
np.sum(new_arr)

406

In [93]:
# 16. standard deviation 
np.std(new_arr)

7.2513600256932635

In [94]:
# 17. square root
np.sqrt(new_arr)

array([[1.        , 3.16227766, 4.89897949, 3.16227766, 4.        ,
        3.        ],
       [2.23606798, 4.47213595, 2.        , 5.38516481, 2.82842712,
        3.31662479],
       [4.58257569, 5.        , 2.82842712, 2.64575131, 3.87298335,
        3.16227766],
       [4.58257569, 4.35889894, 4.89897949, 2.82842712, 2.82842712,
        4.        ],
       [3.60555128, 1.        , 4.58257569, 3.31662479, 3.60555128,
        4.24264069]])

In [95]:
# 18. shape of the array
new_arr.shape

(5, 6)

In [96]:
# 19. Slicing
new_arr[2:, 1:]

array([[25,  8,  7, 15, 10],
       [19, 24,  8,  8, 16],
       [ 1, 21, 11, 13, 18]])

In [98]:
# 20. broadcasting
new_arr[3:, 4:] = 99
new_arr

array([[ 1, 10, 24, 10, 16,  9],
       [ 5, 20,  4, 29,  8, 11],
       [21, 25,  8,  7, 15, 10],
       [21, 19, 24,  8, 99, 99],
       [13,  1, 21, 11, 99, 99]])