In [51]:
import numpy as np

In [52]:
# Creating sample array
arr = np.arange(5, 21)

In [53]:
# Show
arr

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [54]:
# get a value at an index
arr[8]

13

In [55]:
# Get values in a range
arr[1:]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [56]:
# Get values in a range
arr[:5]

array([5, 6, 7, 8, 9])

In [57]:
# Get values in a range
arr[1:5]

array([6, 7, 8, 9])

In [58]:
# Array of range 5 - 25
narr = np.arange(5, 26)

In [59]:
# Show Array
narr

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25])

In [60]:
# Slice array to get range of values
narr[8:17]

array([13, 14, 15, 16, 17, 18, 19, 20, 21])

In [61]:
# Reset arr
arr = np.arange(0, 11)

# BROADCASTING

In [62]:
# Show arr
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [63]:
slice_of_arr = arr[0:6]
# Change slice
slice_of_arr[:] = 99

# show slice again
slice_of_arr


array([99, 99, 99, 99, 99, 99])

In [64]:
# To get a copy we need to be explicit
arr_copy = arr.copy()


In [65]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

# Indexing 2-d arrays

In [66]:
arr_2d = np.array(([5,10,15], [20,25,30], [35,40,45]))
# show arr_2d
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [67]:
arr_2d[1]

array([20, 25, 30])

In [68]:
# Format is arr_2d[row][col] or arr_2d[row, col]

# Getting individual element value
arr_2d[1][0]


20

In [69]:
arr_2d[1, 0]

20

In [70]:
# 2d array slicing
# Accessing multiple rows and columns

#shape(2,2) from top right corner
arr_2d[:2, 1:]

array([[10, 15],
       [25, 30]])

In [71]:
arr_2d[2:]

array([[35, 40, 45]])

In [72]:
arr2d = np.zeros((10,10))

In [73]:
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [74]:
arr_length = len(arr2d)

In [79]:
for i in range(arr_length):
    arr2d[i] = i
    
arr2d

IndexError: index 10 is out of bounds for axis 0 with size 10

In [78]:
arr2d[[6,4,2,7]]

array([[6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.]])

In [80]:
# Selection
# Using brackets for selection based of comparison operators
arr = np.arange(1, 11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [81]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [83]:
bool_arr = arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [84]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [85]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [89]:
arr[arr > 2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [90]:
# Numpy operations

arr = np.arange(0, 10)

In [91]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [92]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [93]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [94]:
arr/arr

<ipython-input-94-50b4ced5627e>:1: RuntimeWarning: invalid value encountered in true_divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [95]:
1/arr

<ipython-input-95-016353831300>:1: RuntimeWarning: divide by zero encountered in true_divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [96]:
# Calculating exponential
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [97]:
np.max(arr)

9

In [98]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [99]:
np.log(arr)

<ipython-input-99-a67b4ae04e95>:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])